name: Build, Tag, and Deploy Docker Image with Slack Notification

on:
  push:
    branches: [ master ]
    tags:     [ '*' ]  # Trigger on any tag push as well

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: lokeshimmadi/lokesh-codes

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tags
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
          else
            VERSION_TAG=$(date +'%Y-%m-%d')
          fi

          echo "version_tag=$VERSION_TAG" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:render-dep

      - name: Trigger Deploy on Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}